### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by WinWinHost** [JedWatson/react-codemirror#140]
I'm having a bit of a bad day. *sigh*
On Mac with NPM 5.8
NodeJS v9.4.0

Let me know if you need more info, thanks in advance.

```
RBAINDOU-M-4116:react-codemirror robert$ sudo npm install
Password:
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.1.3 install /Users/robert/projects/react-codemirror/node_modules/fsevents
> node install

[fsevents] Success: "/Users/robert/projects/react-codemirror/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1176 packages from 1298 contributors in 31.572s
RBAINDOU-M-4116:react-codemirror robert$ npm start

> react-codemirror@1.0.0 start /Users/robert/projects/react-codemirror
> gulp dev

/Users/robert/projects/react-codemirror/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/robert/projects/react-codemirror/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/robert/projects/react-codemirror/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/robert/projects/react-codemirror/node_modules/react-component-gulp-tasks/tasks/release.js:1:73)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-codemirror@1.0.0 start: `gulp dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-codemirror@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robert/.npm/_logs/2018-04-05T19_01_47_360Z-debug.log
RBAINDOU-M-4116:react-codemirror robert$
```

**Comment by scniro** [comment]
@WinWinHost This lib is pretty much abandoned. Check out [react-codemirror2](https://github.com/scniro/react-codemirror2). Check out [gulp-clean-css](https://github.com/scniro/gulp-clean-css) too while you're at it 😉 

> npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
