### ISSUE TITLE
Cannot run the demo app

### ISSUE THREAD

**Issue by mukeshsoni** [JedWatson/react-codemirror#76]
I tried using react-codemirror in an electron app but it doesn't show the editor at all. So i tried running the demo app in this repo but get the following build error - 

```
Browserify Error { Error: Cannot find module 'browserify-optional' from '/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/react-dom-polyfill'
    at /Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:46:17
    at process (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:92:31)
    at /Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object], [Object] ],
     length: 2,
     label: 'deps' } }
[19:09:56] Browserify Error { Error: Cannot find module 'browserify-optional' from '/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/react-dom-polyfill'
    at /Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:46:17
    at process (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:92:31)
    at /Users/mukeshsoni/Desktop/test/react-codemirror/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object], [Object] ],
     length: 2,
     label: 'deps' } }
```

I don't know if the problems in electron app usage are also due to browserify errors.

**Comment by wickedest** [comment]
Waiting merge: https://github.com/JedWatson/react-codemirror/pull/78

**Comment by JedWatson** [comment]
Just fixed this, thanks for the report!

**Comment by mukeshsoni** [comment]
Thanks @JedWatson !
